---
- name: Does essential Tasks when setting up a server with debian
  hosts: all
  gather_facts: false
  tasks:

    - name: Update cache and upgrade system
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: safe

    - name: Install sudo # may put that package into the isntall packages loopg
      ansible.builtin.apt:
        name: sudo
        state: present
        update_cache: true

    - name: Create new group called admind.
      ansible.builtin.group:
        name: admind
        state: present

    - name: Create a new user called admind and add him to groups admind and sudo.
      ansible.builtin.user:
        name: admind # change to desired username
        comment: System Administrator # change to desired full Name or remove Line
        password: '$6$BwNZ3HGxLLVOJ0nh$dBD6Ub3OENWBJjNdD3cPkBEzhciIJEZXXO0JBFCWn6mvJlwYn0wgDw9QpaiH8gDtjhoJctYEX4f.mzRV9lr450' # hashed password
        uid: 1000 # Set a UserID above 1000 because <1000 is for system Users
        groups: admind, sudo,
        create_home: true
        shell: /bin/bash

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - mc
        - htop
        - micro
        - unattended-upgrades
        - gnupg

    - name: Create .ssh direcory
      ansible.builtin.file:
        path: "/home/admind/.ssh/"
        state: directory
        owner: admind
        group: admind
        mode: '0744'
    - name: Create authorized_keys file
      ansible.builtin.file:
        path: "/home/admind/.ssh/authorized_keys"
        state: touch
        owner: admind
        group: admind
        mode: '0644'
    - name: Copy public-key into authorized_keys file
      ansible.builtin.lineinfile:
        path: "/home/admind/.ssh/authorized_keys"
        line: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICp39Dq3npgj7QSoZXRAEQlEs8ATEPj+a8s+LYptNeli steve@steve-t480"

    - name: Update SSH configuration to be more secure (thanks Jeff!)
      ansible.builtin.lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: 'sshd -T -f %s'
        mode: '0644'
      with_items:
        - regexp: "^PasswordAuthentication"
          line: "PasswordAuthentication no"
        - regexp: "^PermitRootLogin"
          line: "PermitRootLogin no"
      #  - regexp: "^Port"
      #    line: "Port {{ ssh_port }}"
      #  - regexp: "^UseDNS"
      #    line: "UseDNS no"
        - regexp: "^PermitEmptyPasswords"
          line: "PermitEmptyPasswords no"
        - regexp: "^PublicKeyAuthentication"
          line: "PublicKeyAuthentication yes"
        - regexp: "^ChallengeResponseAuthentication"
          line: "ChallengeResponseAuthentication no"
       # - regexp: "^GSSAPIAuthentication"
      #  line: "GSSAPIAuthentication no"
       # - regexp: "^X11Forwarding"
       #   line: "X11Forwarding no"
      notify: Restart SSH daemon
